{
 "title": "alerting-dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "告警总量",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "严重",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{severity=\"critical\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "警告",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{severity=\"warning\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "信息",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{severity=\"info\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "告警信息",
   "type": "alertlist",
   "gridPos": { "h": 36, "w": 24, "x": 0, "y": 15 },
   "targets": [
    { "expr": "ALERTS" }
   ]
  }
 ]
}