{
 "title": "ceph-exporter",
 "description": "Overview of Ceph cluster.",
 "tags": [ "ceph-mixin" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "集群状态", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "健康状态",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(ceph_health_status)" }
   ]
  },
  {
   "title": "监视器数目",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(ceph_monitor_quorum_count)" }
   ]
  },
  {
   "title": "管理器活跃数目",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ceph_mgrs_active)" }
   ]
  },
  {
   "title": "OSD 总数目",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(ceph_osds)" }
   ]
  },
  {
   "title": "OSD IN 数目",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(ceph_osds_in)" }
   ]
  },
  {
   "title": "OSD OUT 数目",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osds)-avg(ceph_osds_in)"
    }
   ]
  },
  {
   "title": "OSD UP 数目",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(ceph_osds_up)" }
   ]
  },
  {
   "title": "OSD DOWN 数目",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(ceph_osds_down)" }
   ]
  },
  {
   "title": "读 吞吐量",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(ceph_client_io_read_bytes)" }
   ]
  },
  {
   "title": "写 吞吐量",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ceph_client_io_write_bytes)"
    }
   ]
  },
  {
   "title": "读 IOPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(ceph_client_io_read_ops)" }
   ]
  },
  {
   "title": "写 IOPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(ceph_client_io_write_ops)" }
   ]
  },
  {
   "title": "OSD平均提交时延",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_perf_commit_latency_seconds)*1000"
    }
   ]
  },
  {
   "title": "OSD平均应用时延",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_perf_apply_latency_seconds)*1000"
    }
   ]
  },
  { "title": "集群容量", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "OSD总容量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(ceph_osd_total_bytes)" }
   ]
  },
  {
   "title": "OSD容量使用率",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_total_used_bytes/ceph_osd_total_bytes)"
    }
   ]
  },
  {
   "title": "池总数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(count by (instance) (ceph_pool_available_bytes))"
    }
   ]
  },
  {
   "title": "池已使用容量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (pool) (ceph_pool_used_bytes{pool!~\"default.*|.rgw.root\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OSD已使用容量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(ceph_osd_total_used_bytes)" }
   ]
  },
  {
   "title": "PG总数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(ceph_total_pgs)" }
   ]
  },
  {
   "title": "集群Objects",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "avg(ceph_cluster_objects)", "legendFormat": "Total" },
    { "expr": "avg(ceph_degraded_objects)", "legendFormat": "Degraded" },
    { "expr": "avg(ceph_misplaced_objects)", "legendFormat": "Misplaced" }
   ]
  },
  {
   "title": "PG状态",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "avg(ceph_active_pgs)", "legendFormat": "Active" },
    { "expr": "avg(ceph_backfill_wait_pgs)", "legendFormat": "Backfill wait" },
    { "expr": "avg(ceph_backfilling_pgs)", "legendFormat": "Backfilling" },
    { "expr": "avg(ceph_deep_scrubbing_pgs)", "legendFormat": "Deep scrubbing" },
    { "expr": "avg(ceph_degraded_pgs)", "legendFormat": "Degraded" },
    { "expr": "avg(ceph_down_pgs)", "legendFormat": "Down" },
    { "expr": "avg(ceph_forced_backfill_pgs)", "legendFormat": "Forced backfill" },
    { "expr": "avg(ceph_forced_recovery_pgs)", "legendFormat": "Forced recovery" },
    { "expr": "avg(ceph_incomplete_pgs)", "legendFormat": "Incomplete" },
    { "expr": "avg(ceph_inconsistent_pgs)", "legendFormat": "Inconsistent" },
    { "expr": "avg(ceph_peering_pgs)", "legendFormat": "Peering" },
    { "expr": "avg(ceph_recovering_pgs)", "legendFormat": "Recovering" },
    { "expr": "avg(ceph_recovery_wait_pgs)", "legendFormat": "Recovery wait" },
    { "expr": "avg(ceph_repairing_pgs)", "legendFormat": "Repairing" },
    { "expr": "avg(ceph_scrubbing_pgs)", "legendFormat": "Scrubbing" },
    { "expr": "avg(ceph_snaptrim_pgs)", "legendFormat": "Snaptrim" },
    { "expr": "avg(ceph_snaptrim_wait_pgs)", "legendFormat": "Snaptrim wait" },
    { "expr": "avg(ceph_stale_pgs)", "legendFormat": "Stale" },
    { "expr": "avg(ceph_unclean_pgs)", "legendFormat": "Unclean" },
    { "expr": "avg(ceph_undersized_pgs)", "legendFormat": "Undersized" }
   ]
  },
  {
   "title": "卡住的PG (Stuck PGs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "avg(ceph_degraded_pgs)", "legendFormat": "Degraded" },
    { "expr": "avg(ceph_stale_pgs)", "legendFormat": "Stale" },
    { "expr": "avg(ceph_unclean_pgs)", "legendFormat": "Unclean" },
    { "expr": "avg(ceph_undersized_pgs)", "legendFormat": "Undersized" }
   ]
  },
  { "title": "集群性能", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "avg(ceph_client_io_read_ops)", "legendFormat": "Read" },
    { "expr": "avg(ceph_client_io_write_ops)", "legendFormat": "Write" }
   ]
  },
  {
   "title": "吞吐量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "avg(ceph_client_io_read_bytes)", "legendFormat": "Read" },
    {
     "expr": "avg(ceph_client_io_write_bytes)",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "OSD应用时延分布",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "avg by (osd) (ceph_osd_perf_apply_latency_seconds*1000)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "OSD提交时延分布",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "avg by (osd) (ceph_osd_perf_commit_latency_seconds*1000)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "池配额大小",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (pool) (ceph_pool_quota_max_bytes{pool!~\"default.*|.rgw.root\"})"
    }
   ]
  },
  {
   "title": "池objects配额",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (pool) (ceph_pool_quota_max_objects{pool!~\"default.*|.rgw.root\"})"
    }
   ]
  }
 ]
}