{
 "title": "Cinder",
 "time": { "from": "now-2h", "to": "now" },
 "panels": [
  {
   "title": "Cinder Agents Down",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(openstack_cinder_agent_state{adminState=\"enabled\"})-sum(openstack_cinder_agent_state{adminState=\"enabled\"})"
    }
   ]
  },
  {
   "title": "Cinder Agents Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "count(openstack_cinder_agent_state{adminState=\"enabled\"})"
    }
   ]
  },
  {
   "title": "Cinder Volumes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "targets": [
    { "expr": "openstack_cinder_volumes" }
   ]
  },
  {
   "title": "Cinder Snapshots",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "targets": [
    { "expr": "openstack_cinder_snapshots" }
   ]
  },
  {
   "title": "Tenant Volumes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none", "label": "GiB" }
   ],
   "targets": [
    {
     "expr": "openstack_cinder_limits_volume_used_gb",
     "legendFormat": "{{tenant}} used"
    },
    {
     "expr": "openstack_cinder_limits_volume_max_gb",
     "legendFormat": "{{tenant}} quota"
    }
   ]
  },
  {
   "title": "Pool status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "none", "label": "GiB" }
   ],
   "targets": [
    {
     "expr": "openstack_cinder_pool_capacity_free_gb",
     "legendFormat": "{{volume_backend_name}} free"
    },
    {
     "expr": "openstack_cinder_pool_capacity_total_gb",
     "legendFormat": "{{volume_backend_name}} total"
    }
   ]
  },
  {
   "title": "Cinder Service details",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "targets": [
    { "expr": "openstack_cinder_agent_state" }
   ]
  },
  {
   "title": "Cinder Volumes details",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "targets": [
    { "expr": "openstack_cinder_volume_status" }
   ]
  }
 ]
}