{
 "title": "物理主机监控详情",
 "description": "添加了个分区节点数查看。添加了个人使用的标签。如需修改，请大家修改原版：1 Node Exporter for Prometheus Dashboard CN v20200628 by StarsL.cn，https://grafana.com/grafana/dashboards/8919",
 "tags": [
  "Prometheus",
  "node_exporter",
  "StarsL.cn"
 ],
 "time": { "from": "now-2h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "主机名",
    "query": {
     "query": "label_values(node_uname_info , nodename)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(node_uname_info{nodename=~\"$hostname\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "运行时间",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - node_boot_time_seconds{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "CPU 核数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{instance=~\"$node\", mode='system'})"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "总CPU使用率"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "(1 - ((node_memory_SwapFree_bytes{instance=~\"$node\"} + 1)/ (node_memory_SwapTotal_bytes{instance=~\"$node\"} + 1))) * 100",
     "legendFormat": "交换分区使用率"
    }
   ]
  },
  {
   "title": "【$show_hostname】：各分区可用空间(EXT.*/XFS)",
   "type": "table-old",
   "description": "本看板中的：磁盘总量、使用量、可用量、使用率保持和df命令的Size、Used、Avail、Use% 列的值一致，并且Use%的值会四舍五入保留一位小数，会更加准确。\n\n注：df中Use%算法为：(size - free) * 100 / (avail + (size - free))，结果是整除则为该值，非整除则为该值+1，结果的单位是%。\n参考df命令源码：",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0",
     "legendFormat": "总量"
    },
    {
     "expr": "node_filesystem_avail_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))"
    }
   ]
  },
  {
   "title": "网卡每小时流量",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "上传（-）/下载（+）" }
   ],
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{instance=~\"$node\", device !~ \"qbr.*|qvb.*|qvo.*|tap.*|veth.*|br-.*|docker.*|ovs-.*|vxlan.*\"}[60m])",
     "legendFormat": "{{device}}_in下载"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{instance=~\"$node\", device !~ \"qbr.*|qvb.*|qvo.*|tap.*|veth.*|br-.*|docker.*|ovs-.*|vxlan.*\"}[60m])",
     "legendFormat": "{{device}}_out上传"
    }
   ]
  },
  {
   "title": "总内存",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU iowait",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m])) by (instance))*100",
     "legendFormat": "CPU-总使用率"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[5m])) by (instance) *100",
     "legendFormat": "CPU-系统使用率"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[5m])) by (instance) *100",
     "legendFormat": "CPU-用户使用率"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[5m])) by (instance) *100",
     "legendFormat": "CPU-IO等待使用率"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"nice\",instance=~\"$node\"}[5m])) by (instance) *100",
     "legendFormat": "CPU-Nice使用率"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"steal\",instance=~\"$node\"}[5m])) by (instance) *100",
     "legendFormat": "CPU-Steal使用率"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"irq\",instance=~\"$node\"}[5m])) by (instance) *100",
     "legendFormat": "CPU-Irq使用率"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"softirq\",instance=~\"$node\"}[5m])) by (instance) *100",
     "legendFormat": "CPU-Softirq使用率"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"guest\",instance=~\"$node\"}[5m])) by (instance) *100",
     "legendFormat": "CPU-Guest使用率"
    }
   ]
  },
  {
   "title": "内存使用量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "总内存"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "已用 + 缓存"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemFree_bytes{instance=~\"$node\"} - node_memory_Buffers_bytes{instance=~\"$node\"} - node_memory_Cached_bytes{instance=~\"$node\"} - node_memory_Slab_bytes{instance=~\"$node\"}",
     "legendFormat": "已用"
    }
   ]
  },
  {
   "title": "网卡每秒网络带宽使用",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "bps", "label": "上传（-）/下载（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'$node',  device !~ \"qbr.*|qvb.*|qvo.*|tap.*|veth.*|br-.*|docker.*|ovs-.*|vxlan.*\"}[5m])*8",
     "legendFormat": "{{device}}_in下载"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'$node',  device !~ \"qbr.*|qvb.*|qvo.*|tap.*|veth.*|br-.*|docker.*|ovs-.*|vxlan.*\"}[5m])*8",
     "legendFormat": "{{device}}_out上传"
    }
   ]
  },
  {
   "title": "系统平均负载",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "1分钟负载"
    },
    {
     "expr": "node_load5{instance=~\"$node\"}",
     "legendFormat": "5分钟负载"
    },
    {
     "expr": "node_load15{instance=~\"$node\"}",
     "legendFormat": "15分钟负载"
    },
    {
     "expr": " sum(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu,instance)) by(instance)",
     "legendFormat": "CPU总核数"
    }
   ]
  },
  {
   "title": "每秒磁盘读写容量",
   "type": "graph",
   "description": "Read bytes 每个磁盘分区每秒读取的比特数\nWritten bytes 每个磁盘分区每秒写入的比特数",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "Bps", "label": "读取（-）/写入（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$node\"}[5m])",
     "legendFormat": "{{device}}_读取"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$node\"}[5m])",
     "legendFormat": "{{device}}_写入"
    }
   ]
  },
  {
   "title": "文件分区使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100.0 - 100 * (node_filesystem_avail_bytes{instance=~'$node',device !~'tmpfs',device!~'by-uuid'} / node_filesystem_size_bytes{instance=~'$node',device !~'tmpfs',device!~'by-uuid'}) or 100.0 - 100 * (node_filesystem_avail_bytes{instance=~'$node',device !~'tmpfs',device!~'by-uuid'} / node_filesystem_size_bytes{instance=~'$node',device !~'tmpfs',device!~'by-uuid'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "磁盘读写速率（IOPS）",
   "type": "graph",
   "description": "Reads completed: 每个磁盘分区每秒读完成次数\n\nWrites completed: 每个磁盘分区每秒写完成次数\n\nIO now 每个磁盘分区每秒正在处理的输入/输出请求数",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "iops", "label": "读取（-）/写入（+）I/O ops/sec" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$node\"}[5m])",
     "legendFormat": "{{device}}_读取"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$node\"}[5m])",
     "legendFormat": "{{device}}_写入"
    }
   ]
  },
  {
   "title": "每1秒内I/O操作耗时占比",
   "type": "graph",
   "description": "每一秒钟的自然时间内，花费在I/O上的耗时。（wall-clock time）\n\nnode_disk_io_time_seconds_total：\n磁盘花费在输入/输出操作上的秒数。该值为累加值。（Milliseconds Spent Doing I/Os）\n\nirate(node_disk_io_time_seconds_total[1m])：\n计算每秒的速率：(last值-last前一个值)/时间戳差值，即：1秒钟内磁盘花费在I/O操作的时间占比。",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node\"}[5m])",
     "legendFormat": "{{device}}_每秒I/O操作%"
    }
   ]
  },
  {
   "title": "每次IO读写的耗时（参考：小于100ms）(beta)",
   "type": "graph",
   "description": "Read time seconds 每个磁盘分区读操作花费的秒数\n\nWrite time seconds 每个磁盘分区写操作花费的秒数\n\nIO time seconds 每个磁盘分区输入/输出操作花费的秒数\n\nIO time weighted seconds每个磁盘分区输入/输出操作花费的加权秒数",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "s", "label": "读取（-）/写入（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$node\"}[5m]) / irate(node_disk_reads_completed_total{instance=~\"$node\"}[5m])",
     "legendFormat": "{{device}}_读取"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$node\"}[5m]) / irate(node_disk_writes_completed_total{instance=~\"$node\"}[5m])",
     "legendFormat": "{{device}}_写入"
    }
   ]
  },
  {
   "title": "网络Socket连接信息",
   "type": "graph",
   "description": "Sockets_used - 已使用的所有协议套接字总量\n\nCurrEstab - 当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数\n\nTCP_alloc - 已分配（已建立、已申请到sk_buff）的TCP套接字数量\n\nTCP_tw - 等待关闭的TCP连接数\n\nUDP_inuse - 正在使用的 UDP 套接字数量\n\nRetransSegs - TCP 重传报文数\n\nOutSegs - TCP 发送的报文数\n\nInSegs - TCP 接收的报文数",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node'}",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~'$node'}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{instance=~'$node'}",
     "legendFormat": "Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{instance=~'$node'}",
     "legendFormat": "UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~'$node'}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "irate(node_netstat_Tcp_InSegs{instance=~'$node'}[5m])",
     "legendFormat": "Tcp_InSegs"
    },
    {
     "expr": "irate(node_netstat_Tcp_OutSegs{instance=~'$node'}[5m])",
     "legendFormat": "Tcp_OutSegs"
    },
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs{instance=~'$node'}[5m])",
     "legendFormat": "Tcp_RetransSegs"
    }
   ]
  },
  {
   "title": "打开的文件描述符(左 )/每秒上下文切换次数(右)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "使用的文件描述符" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$node\"}",
     "legendFormat": "使用的文件描述符"
    },
    {
     "expr": "irate(node_context_switches_total{instance=~\"$node\"}[5m])",
     "legendFormat": "每秒上下文切换次数"
    }
   ]
  },
  {
   "title": "总文件描述符",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_filefd_maximum{instance=~\"$node\"})"
    }
   ]
  }
 ]
}