{
 "title": "Prometheus memcached",
 "description": "Prometheus dashboard for memcached servers",
 "tags": [
  "prometheus",
  "memcached"
 ],
 "time": { "from": "now-2h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(memcached_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "% Hit ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (memcached_commands_total{instance=~\"$node\", status=\"miss\"})  / sum (memcached_commands_total{instance=~\"$node\"}) ",
     "legendFormat": "hit ratio"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (memcached_current_connections{instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Get / Set ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (memcached_commands_total{instance=~\"$node\", command=\"set\"}) / sum (memcached_commands_total{instance=~\"$node\", command=\"get\"})",
     "legendFormat": "ratio"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (memcached_commands_total{instance=~\"$node\"}) by (command)",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "evicts / reclaims",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(memcached_items_evicted_total{instance=~\"$node\"})",
     "legendFormat": "evicts"
    },
    {
     "expr": "sum(memcached_items_reclaimed_total{instance=~\"$node\"})",
     "legendFormat": "reclaims"
    }
   ]
  },
  {
   "title": "Read / written bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(memcached_read_bytes_total{instance=~\"$node\"}[5m]))",
     "legendFormat": "read from network"
    },
    {
     "expr": "irate(memcached_written_bytes_total{instance=~\"$node\"}[10m])",
     "legendFormat": "written to network"
    }
   ]
  },
  {
   "title": "Total memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(memcached_current_bytes{instance=~\"$node\"}) / sum(memcached_limit_bytes{instance=~\"$node\"})",
     "legendFormat": "% used memory used"
    }
   ]
  },
  {
   "title": "Items in cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (memcached_current_items{instance=~\"$node\"})",
     "legendFormat": "items "
    }
   ]
  }
 ]
}