{
 "title": "Neutron",
 "time": { "from": "now-2h", "to": "now" },
 "panels": [
  {
   "title": "Neutron Agent Down",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(openstack_neutron_agent_state{adminState=\"up\"})-sum(openstack_neutron_agent_state{adminState=\"up\"})"
    }
   ]
  },
  {
   "title": "Neutron Agent Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count(openstack_neutron_agent_state{adminState=\"up\"})"
    }
   ]
  },
  {
   "title": "Neutron Networks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "targets": [
    { "expr": "openstack_neutron_networks" }
   ]
  },
  {
   "title": "Neutron Subnets",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "targets": [
    { "expr": "openstack_neutron_subnets" }
   ]
  },
  {
   "title": "Neutron Security Groups",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "openstack_neutron_security_groups"
    }
   ]
  },
  {
   "title": "Neutron Floating IPs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "targets": [
    { "expr": "openstack_neutron_floating_ips" }
   ]
  },
  {
   "title": "Neutron agent status detail",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "targets": [
    { "expr": "openstack_neutron_agent_state" }
   ]
  }
 ]
}