{
 "title": "Nova",
 "time": { "from": "now-2h", "to": "now" },
 "panels": [
  {
   "title": "Nova Agent Down",
   "type": "stat",
   "description": "Total number down status nova agent",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(openstack_nova_agent_state{adminState=\"enabled\"})-sum(openstack_nova_agent_state{adminState=\"enabled\"})"
    }
   ]
  },
  {
   "title": "Nova Agent Total",
   "type": "stat",
   "description": "Total number of enabled nova agent",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(openstack_nova_agent_state{adminState=\"enabled\"})"
    }
   ]
  },
  {
   "title": "Nova Compute Agent Total",
   "type": "stat",
   "description": "Total number of enabled nova agent",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(openstack_nova_agent_state{adminState=\"enabled\",service=\"nova-compute\"})"
    }
   ]
  },
  {
   "title": "Images Total",
   "type": "stat",
   "description": "Total number of enabled nova agent",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "openstack_glance_images" }
   ]
  },
  {
   "title": "VM  status",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(openstack_nova_server_status{status=\"ACTIVE\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "count(openstack_nova_server_status{status=\"SHUTOFF\"})",
     "legendFormat": "Shutoff"
    },
    {
     "expr": "count(openstack_nova_server_status)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Tenant Virtual Machines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openstack_nova_limits_instances_used",
     "legendFormat": "{{tenant}} vms"
    },
    {
     "expr": "openstack_nova_limits_instances_max",
     "legendFormat": "{{tenant}} quota"
    }
   ]
  },
  {
   "title": "Tenant vCPU cores usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "openstack_nova_limits_vcpus_used",
     "legendFormat": "{{tenant}} used"
    },
    {
     "expr": "openstack_nova_limits_vcpus_max",
     "legendFormat": "{{tenant}} quota"
    }
   ]
  },
  {
   "title": "Tenant memory usage (GiB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "Memory in GiB" }
   ],
   "targets": [
    {
     "expr": "(openstack_nova_limits_memory_used)/ 1024",
     "legendFormat": "{{tenant}} used"
    },
    {
     "expr": "(openstack_nova_limits_memory_max) / 1024",
     "legendFormat": "{{tenant}} quota"
    }
   ]
  },
  {
   "title": "Host local storage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(openstack_nova_local_storage_used_bytes) / 1024 / 1024 / 1024",
     "legendFormat": "{{hostname}} used"
    },
    {
     "expr": "(openstack_nova_local_storage_available_bytes) / 1024 / 1024 / 1024",
     "legendFormat": "{{hostname}} total"
    }
   ]
  },
  {
   "title": "Nova agents details",
   "type": "table-old",
   "description": "Nova agents status details info",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 21 },
   "targets": [
    { "expr": "openstack_nova_agent_state" }
   ]
  }
 ]
}