{
 "title": "TopN Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "topN", "query": "10" }
  ]
 },
 "panels": [
  {
   "title": "TopN Host Cpu Usage",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk($topN, avg by (instance) (100-irate(node_cpu_seconds_total{mode=\"idle\"}[5m])*100))"
    }
   ]
  },
  {
   "title": "TopN Host DiskUsage",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "topk($topN, 100-100*(sum by(instance) (node_filesystem_avail_bytes{device !~'tmpfs',device!~'by-uuid'}) / sum by(instance) (node_filesystem_size_bytes{device !~'tmpfs',device!~'by-uuid'})))"
    }
   ]
  },
  {
   "title": "TopN VM Cpu Cores",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "topk(10, libvirt_domain_info_memory_usage_bytes/1024/1024/1024 * on (domain) group_right count by (domain, instance_name, uuid) (libvirt_domain_info_meta))  \n"
    }
   ]
  },
  {
   "title": "TopN VM Cpu Memory",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "topk(10, libvirt_domain_info_memory_usage_bytes/1024/1024/1024 * on (domain) group_right count by (domain, instance_name, uuid) (libvirt_domain_info_meta))  \n"
    }
   ]
  },
  {
   "title": "TopN VM RX rate",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "topk($topN, irate(libvirt_domain_interface_stats_receive_bytes_total[5m]) * on (domain) group_left count by (domain, instance_name, uuid) (libvirt_domain_info_meta))"
    }
   ]
  },
  {
   "title": "TopN VM TX rate",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "irate(libvirt_domain_interface_stats_transmit_bytes_total[5m]) * on (domain) group_left count by (domain, instance_name, uuid) (libvirt_domain_info_meta)"
    }
   ]
  }
 ]
}