{
 "title": "虚拟机监控详情",
 "description": "虚拟机监控详情页面。",
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "server",
    "query": {
     "query": "label_values(libvirt_up{job=\"libvirt\"}, instance)"
    }
   },
   {
    "name": "vm",
    "query": {
     "query": "label_values(libvirt_domain_info_meta{job=\"libvirt\",instance=~\"$server\"}, instance_name)"
    }
   },
   {
    "name": "id",
    "query": {
     "query": "label_values(libvirt_domain_info_meta{job=\"libvirt\",instance=~\"$server\", instance_name =\"$vm\"}, uuid)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "运行状态",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (domain)(libvirt_domain_info_vstate) * on (domain) group_right count by (domain, instance_name, uuid) (libvirt_domain_info_meta{instance_name=~\"$vm\", uuid=\"$id\"})"
    }
   ]
  },
  {
   "title": "CPU总量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum by (domain) (libvirt_domain_info_virtual_cpus) * on (domain) group_right count by (domain, instance_name, uuid) (libvirt_domain_info_meta{instance_name=~\"$vm\", uuid=\"$id\"}))"
    }
   ]
  },
  {
   "title": "内存总量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum by (domain) (libvirt_domain_info_memory_usage_bytes) * on (domain) group_right count by (domain, instance_name, uuid) (libvirt_domain_info_meta{instance_name=~\"$vm\", uuid=\"$id\"}))/1024/1024/1024"
    }
   ]
  },
  {
   "title": "网络流量",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(libvirt_domain_interface_stats_receive_bytes_total[5m]) * on (domain) group_left count by (domain, instance_name, uuid) (libvirt_domain_info_meta{instance_name=~\"$vm\", uuid=\"$id\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Sent-上传",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(libvirt_domain_interface_stats_transmit_bytes_total[5m]) * on (domain) group_left count by (domain, instance_name, uuid) (libvirt_domain_info_meta{instance_name=~\"$vm\", uuid=\"$id\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Received-下载",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (domain) (libvirt_domain_memory_stats_used_percent) * on (domain) group_right count by (domain, instance_name, uuid) (libvirt_domain_info_meta{instance_name=~\"$vm\", uuid=\"$id\"})"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "avg by (domain) (irate(libvirt_domain_vcpu_time_seconds_total[5m])) *on (domain) group_right count by (domain, instance_name, uuid) (libvirt_domain_info_meta{instance_name=~\"$vm\", uuid=\"$id\"}) * 100",
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (domain) (irate(libvirt_domain_vcpu_time_seconds_total[5m])) *on (domain) group_right count by (domain, instance_name, uuid) (libvirt_domain_info_meta{instance_name=~\"$vm\", uuid=\"$id\"}) *100",
     "legendFormat": "cpu-usage"
    }
   ]
  },
  {
   "title": "内存使用量",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum by (domain) (libvirt_domain_memory_stats_available_bytes - libvirt_domain_memory_stats_usable_bytes) * on (domain) group_right count by (domain, instance_name, uuid) (libvirt_domain_info_meta{instance_name=~\"$vm\", uuid=\"$id\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "memory-usage",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "每秒磁盘读写 IOPS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(libvirt_domain_block_stats_read_requests_total[5m]) * on (domain) group_left count by (domain, instance_name, uuid) (libvirt_domain_info_meta{instance_name=~\"$vm\", uuid=\"$id\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Write {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(libvirt_domain_block_stats_write_requests_total[5m]) * on (domain) group_left count by (domain, instance_name, uuid) (libvirt_domain_info_meta{instance_name=~\"$vm\", uuid=\"$id\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Read {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "每秒磁盘读写数据量",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(libvirt_domain_block_stats_read_bytes_total[5m]) * on (domain) group_left count by (domain, instance_name, uuid) (libvirt_domain_info_meta{instance_name=~\"$vm\", uuid=\"$id\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Write {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(libvirt_domain_block_stats_write_bytes_total[5m]) * on (domain) group_left count by (domain, instance_name, uuid) (libvirt_domain_info_meta{instance_name=~\"$vm\", uuid=\"$id\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Read {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  }
 ]
}