{
 "title": "availability zone",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "az",
    "label": "Availability Zone",
    "query": "label_values(os_nova_hypervisor_vcpus_total, availability_zone)"
   },
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Availability Zone Overview for $az",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "az"
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "content": "<br>\n<br>\n<br>\n<br>\n<h1><center>CPU</center>"
  },
  {
   "title": "CPU total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openstack:availability_zone:cpu:total{availability_zone=\"$az\"}"
    }
   ]
  },
  {
   "title": "CPU used",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "openstack:availability_zone:cpu:used{availability_zone=\"$az\"}"
    }
   ]
  },
  {
   "title": "CPU used rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "openstack:availability_zone:cpu:used{availability_zone=\"$az\"} / openstack:availability_zone:cpu:total{availability_zone=\"$az\"}",
     "legendFormat": "used / total"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "content": "<br>\n<br>\n<br>\n<br>\n<h1><center>Memory"
  },
  {
   "title": "Memory total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "openstack:availability_zone:memory:total{availability_zone=\"$az\"}"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "openstack:availability_zone:memory:used{availability_zone=\"$az\"}"
    }
   ]
  },
  {
   "title": "Memory used rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "openstack:availability_zone:memory:used{availability_zone=\"$az\"} / openstack:availability_zone:memory:total{availability_zone=\"$az\"}",
     "legendFormat": "used / total"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 11 },
   "content": "<br>\n<br>\n<br>\n<br>\n<h1><center>vms</center></h1>"
  },
  {
   "title": "VM total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openstack:availability_zone:vm:total{availability_zone=\"$az\"}"
    }
   ]
  },
  {
   "title": "Active",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(os_instance_vm_states{availability_zone=\"$az\", vm_states=\"active\"})"
    }
   ]
  },
  {
   "title": "Error",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(os_instance_vm_states{availability_zone=\"$az\", vm_states=\"error\"})"
    }
   ]
  },
  {
   "title": "Stopped",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(os_instance_vm_states{availability_zone=\"$az\", vm_states=\"stopped\"})"
    }
   ]
  },
  {
   "title": "Deleted",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(os_instance_vm_states{availability_zone=\"$az\", states=\"deleted\"})"
    }
   ]
  },
  {
   "title": "Resized",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(os_instance_vm_states{availability_zone=\"$az\", vm_states=\"resized\"})"
    }
   ]
  },
  {
   "title": "Building",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(os_instance_vm_states{availability_zone=\"$az\", states=\"building\"})"
    }
   ]
  }
 ]
}