{
 "title": "Ceph-Cluster",
 "description": "Ceph Cluster overview",
 "tags": [
  "ceph",
  "cluster"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "CLUSTER STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ceph Health",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "ceph_health_status" }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    { "expr": "ceph_cluster_total_bytes" }
   ]
  },
  {
   "title": "Available Capacity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ceph_cluster_total_bytes-ceph_cluster_total_used_bytes)/ceph_cluster_total_bytes"
    }
   ]
  },
  {
   "title": "Number of Objects",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(ceph_pool_objects)" }
   ]
  },
  {
   "title": "Bytes Read",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "decbytes",
   "valueName": "delta",
   "targets": [
    { "expr": "sum(ceph_osd_op_r_out_bytes)" }
   ]
  },
  {
   "title": "Monitors In Quorum",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(ceph_mon_quorum_status)" }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    { "expr": "ceph_cluster_total_used_bytes" }
   ]
  },
  {
   "title": "Mon Session Num",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(ceph_mon_num_sessions)" }
   ]
  },
  {
   "title": "Bytes Written",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "format": "decbytes",
   "valueName": "delta",
   "targets": [
    { "expr": "sum(ceph_osd_op_w_in_bytes)" }
   ]
  },
  { "title": "OSD STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "OSDs OUT",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ceph_osd_up) - count(ceph_osd_in)"
    }
   ]
  },
  {
   "title": "OSDs DOWN",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ceph_osd_up == 0.0) OR vector(0)"
    }
   ]
  },
  {
   "title": "PG Total",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(ceph_pg_total)" }
   ]
  },
  {
   "title": "Avg PGs",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "avg(ceph_osd_numpg)" }
   ]
  },
  {
   "title": "Avg Commit Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 8 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(ceph_osd_commit_latency_ms)"
    }
   ]
  },
  {
   "title": "Avg  Op Read Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 8 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(rate(ceph_osd_op_r_latency_sum[10m])/rate(ceph_osd_op_r_latency_count[10m]) >= 0)"
    }
   ]
  },
  {
   "title": "OSDs IN",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(ceph_osd_in)" }
   ]
  },
  {
   "title": "OSDs UP",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(ceph_osd_up)" }
   ]
  },
  {
   "title": "Avg Apply Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 11 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    { "expr": "avg(ceph_osd_apply_latency_ms)" }
   ]
  },
  {
   "title": "Avg Op Write Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 11 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(rate(ceph_osd_op_w_latency_sum[10m]) / rate(ceph_osd_op_w_latency_count[10m]) >= 0)"
    }
   ]
  },
  { "title": "Ceph Versions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Ceph OSD Versions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by (ceph_version)(ceph_osd_metadata)",
     "legendFormat": "{{ceph_version}}"
    }
   ]
  },
  {
   "title": "Ceph Mon Versions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (ceph_version)(ceph_mon_metadata)",
     "legendFormat": "{{ceph_version}}"
    }
   ]
  },
  { "title": "CLUSTER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Capacity",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "ceph_cluster_total_bytes", "legendFormat": "Total Capacity" },
    {
     "expr": "ceph_cluster_total_bytes-ceph_cluster_total_used_bytes",
     "legendFormat": "Available"
    },
    { "expr": "ceph_cluster_total_used_bytes", "legendFormat": "Used" }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w_in_bytes[10m]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(irate(ceph_osd_op_r_out_bytes[10m]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "sum(irate(ceph_osd_op_w[10m]))", "legendFormat": "Write" },
    { "expr": "sum(irate(ceph_osd_op_r[10m]))", "legendFormat": "Read" }
   ]
  },
  {
   "title": "OSD Type Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(ceph_bluestore_commit_lat_count)",
     "legendFormat": "BlueStore"
    },
    {
     "expr": "count(ceph_filestore_journal_latency_count)",
     "legendFormat": "FileStore"
    }
   ]
  },
  {
   "title": "Objects Per Pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(ceph_pool_objects) *on (pool_id) group_left(name)(ceph_pool_metadata)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool Used Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(ceph_pool_stored) *on (pool_id) group_left(name)(ceph_pool_metadata)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool RAW Used Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(ceph_pool_stored_raw) *on (pool_id) group_left(name)(ceph_pool_metadata)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool Quota Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(ceph_pool_quota_bytes) *on (pool_id) group_left(name)(ceph_pool_metadata)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool Objects Quota",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(ceph_pool_quota_objects) *on (pool_id) group_left(name)(ceph_pool_metadata)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "OBJECTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Objects in the Cluster",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(ceph_pool_objects)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Stuck PGs",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceph_pg_degraded", "legendFormat": "Degraded" },
    { "expr": "ceph_pg_stale", "legendFormat": "Stale" },
    { "expr": "ceph_pg_undersized", "legendFormat": "Undersized" }
   ]
  },
  {
   "title": "PGs State",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceph_pg_active", "legendFormat": "Active" },
    { "expr": "ceph_pg_clean", "legendFormat": "Clean" },
    { "expr": "ceph_pg_peering", "legendFormat": "Peering" },
    { "expr": "ceph_pg_degraded", "legendFormat": "Degraded" },
    { "expr": "ceph_pg_stale", "legendFormat": "Stale" },
    { "expr": "ceph_unclean_pgs", "legendFormat": "Unclean" },
    { "expr": "ceph_pg_undersized", "legendFormat": "Undersized" },
    { "expr": "ceph_pg_incomplete", "legendFormat": "Incomplete" },
    { "expr": "ceph_pg_forced_backfill", "legendFormat": "Forced Backfill" },
    { "expr": "ceph_pg_inconsistent", "legendFormat": "Inconsistent" },
    { "expr": "ceph_pg_forced_recovery", "legendFormat": "Forced Recovery" },
    { "expr": "ceph_pg_creating", "legendFormat": "Creating" },
    { "expr": "ceph_pg_wait_backfill", "legendFormat": "Wait Backfill" },
    { "expr": "ceph_pg_deep", "legendFormat": "Deep" },
    { "expr": "ceph_pg_scrubbing", "legendFormat": "Scrubbing" },
    { "expr": "ceph_pg_recovering", "legendFormat": "Recovering" },
    { "expr": "ceph_pg_repair", "legendFormat": "Repair" },
    { "expr": "ceph_pg_down", "legendFormat": "Down" },
    { "expr": "ceph_pg_peered", "legendFormat": "Peered" },
    { "expr": "ceph_pg_backfill", "legendFormat": "Backfill" },
    { "expr": "ceph_pg_remapped", "legendFormat": "Remapped" },
    { "expr": "ceph_pg_backfill_toofull", "legendFormat": "Backfill Toofull" }
   ]
  },
  {
   "title": "Recovery Operations",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_recovery_ops[$interval])) or vector(0)",
     "legendFormat": "OPS"
    }
   ]
  },
  { "title": "LATENCY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "OSD Apply Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "targets": [
    { "expr": "ceph_osd_apply_latency_ms" }
   ]
  },
  {
   "title": "OSD Commit Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "targets": [
    { "expr": "ceph_osd_commit_latency_ms" }
   ]
  },
  {
   "title": "OSD Read Op Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "rate(ceph_osd_op_r_latency_sum[10m]) / rate(ceph_osd_op_r_latency_count[10m]) >= 0"
    }
   ]
  },
  {
   "title": "OSD Write Op Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "targets": [
    {
     "expr": "rate(ceph_osd_op_w_latency_sum[10m]) / rate(ceph_osd_op_w_latency_count[10m]) >= 0 or vector(0)"
    }
   ]
  },
  {
   "title": "Avg OSD  Op  Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(rate(ceph_osd_op_r_latency_sum[10m]) / rate(ceph_osd_op_r_latency_count[10m]) >= 0)",
     "legendFormat": "read"
    },
    {
     "expr": "avg(rate(ceph_osd_op_w_latency_sum[10m]) / rate(ceph_osd_op_w_latency_count[10m]) >= 0)",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "AVG OSD Apply + Commit Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 103 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "avg(ceph_osd_apply_latency_ms)", "legendFormat": "apply" },
    {
     "expr": "avg(ceph_osd_commit_latency_ms)",
     "legendFormat": "commit"
    }
   ]
  }
 ]
}