{
 "title": "HAProxy Metrics",
 "description": "HAProxy metrics and statistics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "server",
    "query": "label_values(haproxy_active_servers, server)"
   },
   {
    "name": "proxy",
    "label": "proxy",
    "query": "label_values(haproxy_active_servers{server=\"$server\"}, proxy)"
   },
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Backend Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Backends Down",
   "type": "singlestat",
   "description": "Number of active servers (backend), server is active (server)",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(haproxy_active_servers{server=\"$server\", status!=\"UP\", type=\"server\", proxy=~\"$proxy\"})"
    }
   ]
  },
  {
   "title": "Backend Status",
   "type": "graph",
   "description": "Number of active servers (backend), server is active (server)\nNumber of backup servers (backend), server is backup (server)",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(haproxy_active_servers{server=\"$server\", status=\"UP\", type=\"backend\", proxy=~\"$proxy\"})",
     "legendFormat": "Active UP"
    },
    {
     "expr": "sum(haproxy_active_servers{server=\"$server\", status!=\"UP\", type=\"backend\", proxy=~\"$proxy\"})",
     "legendFormat": "Active Down"
    },
    {
     "expr": "sum(haproxy_backup_servers{server=\"$server\", status=\"UP\", type=\"backend\", proxy=~\"$proxy\"})",
     "legendFormat": "Backup UP"
    },
    {
     "expr": "sum(haproxy_backup_servers{server=\"$server\", status!=\"UP\", type=\"backend\", proxy=~\"$proxy\"})",
     "legendFormat": "Backup Down"
    }
   ]
  },
  {
   "title": "Backup Backends Down",
   "type": "singlestat",
   "description": "Number of backup servers (backend), server is backup (server)",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(haproxy_backup_servers{server=\"$server\", status!=\"UP\", type=\"backend\", proxy=~\"$proxy\"})"
    }
   ]
  },
  { "title": "Sessions & Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Sessions/s Frontend over Backend",
   "type": "graph",
   "description": "Number of sessions per second over last elapsed second",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(haproxy_rate{server=\"$server\", proxy=~\"$proxy\", type=\"frontend\"})",
     "legendFormat": "Frontend"
    },
    {
     "expr": "sum(haproxy_rate{server=\"$server\", proxy=~\"$proxy\", type=\"backend\"})",
     "legendFormat": "Backend"
    }
   ]
  },
  {
   "title": "Frontend Requests/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(haproxy_req_rate{server=\"$server\", proxy=~\"$proxy\"})",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Current Queued Requests",
   "type": "graph",
   "description": "Current queued requests. For the backend this reports the number queued without a server assigned.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(haproxy_qcur{server=\"$server\", proxy=~\"$proxy\", type=\"backend\"})",
     "legendFormat": "Queued Requests"
    }
   ]
  },
  { "title": "HTTP Response Codes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "HTTP Response Rate by Code Frontend over Backend",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_http_response_1xx{server=\"$server\", proxy=~\"$proxy\", type=\"frontend\"}[5m]))",
     "legendFormat": "Frontend 1xx"
    },
    {
     "expr": "sum(rate(haproxy_http_response_1xx{server=\"$server\", proxy=~\"$proxy\", type=\"backend\"}[5m]))",
     "legendFormat": "Backend 1xx"
    },
    {
     "expr": "sum(rate(haproxy_http_response_2xx{server=\"$server\", proxy=~\"$proxy\", type=\"frontend\"}[5m]))",
     "legendFormat": "Frontend 2xx"
    },
    {
     "expr": "sum(rate(haproxy_http_response_2xx{server=\"$server\", proxy=~\"$proxy\", type=\"backend\"}[5m]))",
     "legendFormat": "Backend 2xx"
    },
    {
     "expr": "sum(rate(haproxy_http_response_3xx{server=\"$server\", proxy=~\"$proxy\", type=\"frontend\"}[5m]))",
     "legendFormat": "Frontend 3xx"
    },
    {
     "expr": "sum(rate(haproxy_http_response_3xx{server=\"$server\", proxy=~\"$proxy\", type=\"backend\"}[5m]))",
     "legendFormat": "Backend 3xx"
    },
    {
     "expr": "sum(rate(haproxy_http_response_4xx{server=\"$server\", proxy=~\"$proxy\", type=\"frontend\"}[5m]))",
     "legendFormat": "Frontend 4xx"
    },
    {
     "expr": "sum(rate(haproxy_http_response_4xx{server=\"$server\", proxy=~\"$proxy\", type=\"backend\"}[5m]))",
     "legendFormat": "Backend 4xx"
    },
    {
     "expr": "sum(rate(haproxy_http_response_5xx{server=\"$server\", proxy=~\"$proxy\", type=\"frontend\"}[5m]))",
     "legendFormat": "Frontend 5xx"
    },
    {
     "expr": "sum(rate(haproxy_http_response_5xx{server=\"$server\", proxy=~\"$proxy\", type=\"backend\"}[5m]))",
     "legendFormat": "Backend 5xx"
    },
    {
     "expr": "sum(rate(haproxy_http_response_other{server=\"$server\", proxy=~\"$proxy\", type=\"frontend\"}[5m]))",
     "legendFormat": "Frontend Other"
    },
    {
     "expr": "sum(rate(haproxy_http_response_other{server=\"$server\", proxy=~\"$proxy\", type=\"backend\"}[5m]))",
     "legendFormat": "Backend Other"
    }
   ]
  },
  { "title": "Data Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Data Rate Bytes IN over OUT",
   "type": "graph",
   "description": "bin [LFBS]: bytes in\nbout [LFBS]: bytes out",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_bin{server=\"$server\", proxy=~\"$proxy\", type=\"frontend\"}[5m]))",
     "legendFormat": "Frontend IN"
    },
    {
     "expr": "sum(rate(haproxy_bin{server=\"$server\", proxy=~\"$proxy\", type=\"backend\"}[5m]))",
     "legendFormat": "Backend IN"
    },
    {
     "expr": "sum(rate(haproxy_bout{server=\"$server\", proxy=~\"$proxy\", type=\"frontend\"}[5m]))",
     "legendFormat": "Frontend OUT"
    },
    {
     "expr": "sum(rate(haproxy_bout{server=\"$server\", proxy=~\"$proxy\", type=\"backend\"}[5m]))",
     "legendFormat": "Backend OUT"
    }
   ]
  }
 ]
}