{
 "title": "host aggregate",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ha",
    "label": "host aggregate",
    "query": "label_values(openstack:host_aggregate:cpu:total, ha_name)"
   },
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "host aggregate overview for $ha",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "ha"
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "content": "<br>\n<br>\n<br>\n<h1><center>CPU</center></h1>"
  },
  {
   "title": "CPU total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openstack:host_aggregate:cpu:total{ha_name=\"$ha\"}"
    }
   ]
  },
  {
   "title": "CPU used",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openstack:host_aggregate:cpu:used{ha_name=\"$ha\"}"
    }
   ]
  },
  {
   "title": "use rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "openstack:host_aggregate:cpu:used{ha_name=\"$ha\"} / openstack:host_aggregate:cpu:total{ha_name=\"$ha\"}",
     "legendFormat": "used / total"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "content": "<br>\n<br>\n<br>\n<h1><center>Memory</center><h1>"
  },
  {
   "title": "Memory total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "openstack:host_aggregate:memory:total{ha_name=\"$ha\"}"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "openstack:host_aggregate:memory:used{ha_name=\"$ha\"}"
    }
   ]
  },
  {
   "title": "used rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "openstack:host_aggregate:memory:used{ha_name=\"$ha\"} / openstack:host_aggregate:memory:total{ha_name=\"$ha\"}",
     "legendFormat": "used / total"
    }
   ]
  },
  {
   "title": "host total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(openstack:host_aggregate:host:list{ha_name=\"$ha\"})"
    }
   ]
  },
  {
   "title": "VM total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(openstack:host_aggregate:vm:total{ha_name=\"$ha\"})"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 5, "w": 18, "x": 6, "y": 11 }, "content": "\n" }
 ]
}