{
 "title": "Memcached Metrics",
 "description": "Memcached metrics from a single Telegraf instance",
 "tags": [
  "memcached",
  "prometheus",
  "telegraf"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(memcached_uptime, instance)"
   },
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memcached Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "memcached_uptime{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "singlestat",
   "description": "Number of worker threads requested",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "memcached_threads{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Items",
   "type": "singlestat",
   "description": "Total number of items stored since the server started",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "memcached_total_items{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Connections",
   "type": "singlestat",
   "description": "Total number of connections opened since the server started running",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "memcached_total_connections{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Storage Used",
   "type": "singlestat",
   "description": "Current number of bytes used to store items",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "memcached_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Storage Max",
   "type": "singlestat",
   "description": "Number of bytes this server is allowed to use for storage",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "memcached_limit_maxbytes{instance=\"$instance\"}"
    }
   ]
  },
  { "title": "Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Storage Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(memcached_bytes{instance=\"$instance\"} / memcached_limit_maxbytes{instance=\"$instance\"}) * 100",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Current Items",
   "type": "graph",
   "description": "Current number of items stored",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "memcached_curr_items{instance=\"$instance\"}",
     "legendFormat": "items"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "graph",
   "description": "Number of open connections",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "memcached_curr_connections{instance=\"$instance\"}",
     "legendFormat": "connections"
    }
   ]
  },
  {
   "title": "Get Hit %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "memcached_get_hits{instance=\"$instance\"} / (memcached_get_hits{instance=\"$instance\"} + memcached_get_misses{instance=\"$instance\"})",
     "legendFormat": "get_hits %"
    }
   ]
  },
  {
   "title": "Get Hits vs Misses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "memcached_get_hits{instance=\"$instance\"}",
     "legendFormat": "get_hits"
    },
    {
     "expr": "memcached_get_misses{instance=\"$instance\"}",
     "legendFormat": "get_misses"
    }
   ]
  },
  {
   "title": "Evictions",
   "type": "graph",
   "description": "Number of valid items removed from cache to free memory for new items",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "memcached_evictions{instance=\"$instance\"}",
     "legendFormat": "evictions"
    }
   ]
  },
  {
   "title": "Network Bytes Read over Written",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "memcached_bytes_read{instance=\"$instance\"}",
     "legendFormat": "bytes_read"
    },
    {
     "expr": "memcached_bytes_written{instance=\"$instance\"}",
     "legendFormat": "bytes_written"
    }
   ]
  }
 ]
}