{
 "title": "openstack_resource",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "the number of instances",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    { "expr": "count(os_instance_info)" }
   ]
  },
  { "title": "neutron", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "the number of ports",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 9 },
   "targets": [
    { "expr": "count(os_neutron_ports)" }
   ]
  },
  {
   "title": "the number of networks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 11, "y": 9 },
   "targets": [
    { "expr": "count(os_neutron_networks)" }
   ]
  },
  {
   "title": "the number of floating_ips",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "targets": [
    { "expr": "count(os_neutron_floatingips)" }
   ]
  },
  {
   "title": "the number of subnets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 11, "y": 16 },
   "targets": [
    { "expr": "count(os_neutron_subnets)" }
   ]
  },
  {
   "title": "the number of routers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "count(os_neutron_routers)" }
   ]
  },
  { "title": "cinder", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "the number of volumes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "count(os_cinder_volume)" }
   ]
  },
  {
   "title": "the number of volume_types",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "count(os_cinder_volume_type)" }
   ]
  },
  { "title": "glance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "the number of images",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "targets": [
    { "expr": "count(os_glance_image_size)" }
   ]
  },
  { "title": "keystone", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "the number of users",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 39 },
   "targets": [
    { "expr": "count(os_keystone_user)" }
   ]
  },
  {
   "title": "the number of projects",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 39 },
   "targets": [
    { "expr": "count(os_keystone_project)" }
   ]
  },
  {
   "title": "the number of services",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 12, "y": 39 },
   "targets": [
    { "expr": "count(os_keystone_service)" }
   ]
  },
  {
   "title": "the number of roles",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 39 },
   "targets": [
    { "expr": "count(os_keystone_role)" }
   ]
  },
  {
   "title": "The number of domains",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 45 },
   "targets": [
    { "expr": "count(os_keystone_domain)" }
   ]
  },
  {
   "title": "the number of endpoints",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 45 },
   "targets": [
    { "expr": "count(os_keystone_endpoint)" }
   ]
  }
 ]
}