{
 "title": "RabbitMQ Metrics",
 "description": "Basic rabbitmq host stats: Node Stats, Exchanges, Channels, Consumers,  Connections, Queues, Messages, Messages per Queue, Memory, File Descriptors, Sockets.",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "HostName",
    "query": {
     "query": "label_values(rabbitmq_node_running,hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$hostname Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running nodes",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rabbitmq_node_running{hostname=\"$hostname\"}) "
    }
   ]
  },
  {
   "title": "Node up Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_node_running{hostname=~\"$hostname\"}",
     "legendFormat": "node-{{node}}"
    }
   ]
  },
  {
   "title": "Message Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(rabbitmq_overview_messages_published{hostname=~\"$hostname\"}[10m])",
     "legendFormat": "published"
    },
    {
     "expr": "irate(rabbitmq_overview_messages_delivered{hostname=~\"$hostname\"}[10m])",
     "legendFormat": "delivered"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_overview_messages_ready{hostname=~\"$hostname\"}",
     "legendFormat": "ready"
    },
    {
     "expr": "rabbitmq_overview_messages_unacked{hostname=~\"$hostname\"}",
     "legendFormat": "unack"
    },
    {
     "expr": "rabbitmq_overview_messages{hostname=~\"$hostname\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Exchanges",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_overview_exchanges{hostname=~\"$hostname\"}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Channels",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_overview_channels{hostname=~\"$hostname\"}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Queues",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_overview_queues{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_overview_connections{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_overview_consumers{hostname=~\"$hostname\"}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  { "title": "Cluster Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "FIle descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rabbitmq_node_fd_used) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(rabbitmq_node_mem_used) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Erlang Processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rabbitmq_node_proc_used) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "max(rabbitmq_node_uptime) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}