{
 "title": "Services",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Neutron services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "prometheus" },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "content": "\n<br>\n<br>\n<br>\n<h1><center>Total</center>\n\n"
  },
  {
   "title": "DHCP agent total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(os_neutron_agent_alive{agent_type=\"DHCP agent\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "L3 agent total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(os_neutron_agent_alive{agent_type=\"L3 agent\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Metadata agent total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(os_neutron_agent_alive{agent_type=\"Metadata agent\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Open vSwitch agent total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(os_neutron_agent_alive{agent_type=\"Open vSwitch agent\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "content": "<br>\n<br>\n<br>\n<h1><center>Up"
  },
  {
   "title": "neutron-dhcp-agent up",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 6 },
   "repeat": "binary",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(os_neutron_agent_alive{binary=\"neutron-dhcp-agent\", agent_alive=\"True\"})"
    }
   ]
  },
  {
   "title": "neutron-dhcp-agent up",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 6 },
   "repeat": "binary",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(os_neutron_agent_alive{binary=\"neutron-dhcp-agent\", agent_alive=\"True\"})"
    }
   ]
  },
  {
   "title": "neutron-dhcp-agent up",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 6 },
   "repeat": "binary",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(os_neutron_agent_alive{binary=\"neutron-dhcp-agent\", agent_alive=\"True\"})"
    }
   ]
  },
  {
   "title": "neutron-dhcp-agent up",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 6 },
   "repeat": "binary",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(os_neutron_agent_alive{binary=\"neutron-dhcp-agent\", agent_alive=\"True\"})"
    }
   ]
  },
  { "title": "Nova services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }, "repeat": "prometheus" },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 12 },
   "content": "\n<br>\n<br>\n<br>\n<h1><center>Total</center>\n\n"
  },
  {
   "title": "nova-compute service total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(os_nova_services_state{binary=\"nova-compute\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "nova-conductor service total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(os_nova_services_state{binary=\"nova-conductor\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "nova-consoleauth service total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(os_nova_services_state{binary=\"nova-consoleauth\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "nova-scheduler service total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(os_nova_services_state{binary=\"nova-scheduler\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
   "content": "<br>\n<br>\n<br>\n<h1><center>Up"
  },
  {
   "title": "nova-compute Up",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 17 },
   "repeat": "binary",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(os_nova_services_state{binary=\"nova-compute\", services_state=\"up\"})"
    }
   ]
  },
  {
   "title": "nova-conductor Up",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 17 },
   "repeat": "binary",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(os_nova_services_state{binary=\"nova-conductor\", services_state=\"up\"})"
    }
   ]
  },
  {
   "title": "nova-consoleauth Up",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 17 },
   "repeat": "binary",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(os_nova_services_state{binary=\"nova-consoleauth\", services_state=\"up\"})"
    }
   ]
  },
  {
   "title": "nova-scheduler Up",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 17 },
   "repeat": "binary",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(os_nova_services_state{binary=\"nova-scheduler\", services_state=\"up\"})"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 22 },
   "content": "<br>\n<br>\n<br>\n<h1><center>enable</center>\n"
  },
  {
   "title": "nova-compute enabled",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 22 },
   "repeat": "binary",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(os_nova_services_status{binary=\"nova-compute\", services_status=\"enabled\"})"
    }
   ]
  },
  {
   "title": "nova-conductor enabled",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 22 },
   "repeat": "binary",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(os_nova_services_status{binary=\"nova-conductor\", services_status=\"enabled\"})"
    }
   ]
  },
  {
   "title": "nova-consoleauth enabled",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 22 },
   "repeat": "binary",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(os_nova_services_status{binary=\"nova-consoleauth\", services_status=\"enabled\"})"
    }
   ]
  },
  {
   "title": "nova-scheduler enabled",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 22 },
   "repeat": "binary",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(os_nova_services_status{binary=\"nova-scheduler\", services_status=\"enabled\"})"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "VCPUs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "openstack:cpu:used" },
    { "expr": "openstack:cpu:total" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    { "expr": "openstack:memory:used" },
    { "expr": "openstack:memory:total" }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    { "expr": "openstack:storage:used" },
    { "expr": "openstack:storage:total" }
   ]
  }
 ]
}