{
 "title": "VM",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "project_name",
    "label": "Project Name",
    "query": "label_values(virtual:kvm:cpu:count, project_name)"
   },
   {
    "name": "instance_uuid",
    "label": "VM UUID",
    "query": "label_values(virtual:kvm:cpu:count{project_name=\"$project_name\"}, instance_uuid)"
   },
   {
    "name": "instance_name",
    "label": "VM name",
    "query": "label_values(virtual:kvm:cpu:count{project_name=\"$project_name\", instance_uuid=\"$instance_uuid\"}, instance_name)"
   },
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "instance overview for - $instance_uuid",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance_uuid"
  },
  {
   "title": "cpu count",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "virtual:kvm:cpu:count{instance_uuid=~\"$instance_uuid\"}",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "VM State",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(os_instance_vm_states{instance_uuid=\"$instance_uuid\"}) by (vm_states) > 0"
    }
   ]
  },
  {
   "title": "Power State",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "max(os_instance_power_states{instance_uuid=\"$instance_uuid\"})by(power_states) > 0"
    }
   ]
  },
  {
   "title": "cpu load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "virtual:kvm:cpu:usage{instance_uuid=\"$instance_uuid\"}",
     "legendFormat": "load"
    }
   ]
  },
  {
   "title": "memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "virtual:kvm:memory:total{instance_uuid=\"$instance_uuid\"}",
     "legendFormat": "memory total - {{instance_name}}"
    },
    {
     "expr": "virtual:kvm:memory:used{instance_uuid=\"$instance_uuid\"}",
     "legendFormat": "memory used - {{instance_name}}"
    }
   ]
  },
  {
   "title": "network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "virtual:kvm:network:receive:rate{instance_uuid=\"$instance_uuid\"}",
     "legendFormat": "read - {{target_device}}"
    },
    {
     "expr": "virtual:kvm:network:write:rate{instance_uuid=\"$instance_uuid\"}",
     "legendFormat": "write - {{target_device}}"
    }
   ]
  },
  {
   "title": "disk iops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "virtual:kvm:disk:read:iops{instance_uuid=\"$instance_uuid\"}",
     "legendFormat": "read - {{target_device}}"
    },
    {
     "expr": "virtual:kvm:disk:write:iops{instance_uuid=\"$instance_uuid\"}",
     "legendFormat": "write - {{target_device}}"
    }
   ]
  },
  {
   "title": "disk kbps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "virtual:kvm:disk:read:kbps{instance_uuid=\"$instance_uuid\"}",
     "legendFormat": "read - {{target_device}}"
    },
    {
     "expr": "virtual:kvm:disk:write:kbps{instance_uuid=\"$instance_uuid\"}",
     "legendFormat": "write - {{target_device}}"
    }
   ]
  },
  {
   "title": "instance overview for - $instance_uuid",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 }
  },
  {
   "title": "cpu count",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 32 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "virtual:kvm:cpu:count{instance_uuid=~\"$instance_uuid\"}",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "VM State",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(os_instance_vm_states{instance_uuid=\"$instance_uuid\"}) by (vm_states) > 0"
    }
   ]
  },
  {
   "title": "Power State",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "max(os_instance_power_states{instance_uuid=\"$instance_uuid\"})by(power_states) > 0"
    }
   ]
  },
  {
   "title": "cpu load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "virtual:kvm:cpu:usage{instance_uuid=\"$instance_uuid\"}",
     "legendFormat": "load"
    }
   ]
  },
  {
   "title": "memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "virtual:kvm:memory:total{instance_uuid=\"$instance_uuid\"}",
     "legendFormat": "memory total - {{instance_name}}"
    },
    {
     "expr": "virtual:kvm:memory:used{instance_uuid=\"$instance_uuid\"}",
     "legendFormat": "memory used - {{instance_name}}"
    }
   ]
  },
  {
   "title": "network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "virtual:kvm:network:receive:rate{instance_uuid=\"$instance_uuid\"}",
     "legendFormat": "read - {{target_device}}"
    },
    {
     "expr": "virtual:kvm:network:write:rate{instance_uuid=\"$instance_uuid\"}",
     "legendFormat": "write - {{target_device}}"
    }
   ]
  },
  {
   "title": "disk iops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "virtual:kvm:disk:read:iops{instance_uuid=\"$instance_uuid\"}",
     "legendFormat": "read - {{target_device}}"
    },
    {
     "expr": "virtual:kvm:disk:write:iops{instance_uuid=\"$instance_uuid\"}",
     "legendFormat": "write - {{target_device}}"
    }
   ]
  },
  {
   "title": "disk kbps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "virtual:kvm:disk:read:kbps{instance_uuid=\"$instance_uuid\"}",
     "legendFormat": "read - {{target_device}}"
    },
    {
     "expr": "virtual:kvm:disk:write:kbps{instance_uuid=\"$instance_uuid\"}",
     "legendFormat": "write - {{target_device}}"
    }
   ]
  }
 ]
}