{
 "title": "vms overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "vm_state",
    "label": "VM State",
    "query": {
     "query": "label_values(os_instance_vm_states, vm_states)"
    }
   },
   {
    "name": "power_state",
    "label": "Power State",
    "query": {
     "query": "label_values(os_instance_power_states, power_states)"
    }
   },
   { "name": "cpu_usage_top", "label": "CPU usage TOP", "query": "1,2,3,4,5,6,7,8,9,10" },
   { "name": "memory_used_top", "label": "Memory used TOP", "query": "1,2,3,4,5,6,7,8,9,10" },
   { "name": "net_transmit_top", "label": "Net Transmit TOP", "query": "1,2,3,4,5,6,7,8,9,10" },
   { "name": "top_net_receive", "label": "Net Receive TOP", "query": "1,2,3,4,5,6,7,8,9,10" },
   { "name": "top_read_iops", "label": "Disk Read iops Top", "query": "1,2,3,4,5,6,7,8,9,10" },
   { "name": "top_write_iops", "label": "Disk Write iops Top", "query": "1,2,3,4,5,6,7,8,9,10" },
   { "name": "top_read_kbps", "label": "Disk Read kbps Top", "query": "1,2,3,4,5,6,7,8,9,10" },
   { "name": "top_write_kbps", "label": "Disk Write kbps Top", "query": "1,2,3,4,5,6,7,8,9,10" }
  ]
 },
 "panels": [
  { "title": "VMS State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$vm_state",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "repeat": "vm_state",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum(os_instance_vm_states{vm_states=\"$vm_state\"}) by (vm_states, instance_uuid)) by (vm_states)",
     "legendFormat": "{{vm_state}}"
    }
   ]
  },
  { "title": "VMS Power State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "$power_state",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 6 },
   "repeat": "power_state",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(max(os_instance_power_states{power_states=\"$power_state\"}) by (power_states, instance_uuid)) by (power_states)",
     "legendFormat": "{{power_state}}"
    }
   ]
  },
  {
   "title": "$power_state",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(max(os_instance_power_states{power_states=\"$power_state\"}) by (power_states, instance_uuid)) by (power_states)",
     "legendFormat": "{{power_state}}"
    }
   ]
  },
  {
   "title": "$power_state",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(max(os_instance_power_states{power_states=\"$power_state\"}) by (power_states, instance_uuid)) by (power_states)",
     "legendFormat": "{{power_state}}"
    }
   ]
  },
  { "title": "CPU usage TOP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Top $cpu_usage_top - cpu usage ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($cpu_usage_top, virtual:kvm:cpu:usage)",
     "legendFormat": "{{instance_name}} - {{instance_uuid}}"
    }
   ]
  },
  { "title": "Memory used TOP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Top $memory_used_top - memory used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($memory_used_top, virtual:kvm:memory:used)",
     "legendFormat": "{{instance_name}} - {{instance_uuid}}"
    }
   ]
  },
  { "title": "Network TOP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Top $top_net_receive - receive rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($top_net_receive,virtual:kvm:network:receive:rate)",
     "legendFormat": "{{instance_name}} - {{instance_uuid}}"
    }
   ]
  },
  {
   "title": "Top $net_transmit_top Transmit rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($net_transmit_top, virtual:kvm:network:write:rate)",
     "legendFormat": "{{instance_name}} - {{instance_uuid}}"
    }
   ]
  },
  { "title": "Disk TOP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Top $top_read_iops - read iops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($top_read_iops, virtual:kvm:disk:read:iops)",
     "legendFormat": "{{instance_name}} - {{instance_uuid}}"
    }
   ]
  },
  {
   "title": "Top $top_read_kbps - read kbps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($top_read_kbps, virtual:kvm:disk:read:kbps)",
     "legendFormat": "{{instance_name}} - {{instance_uuid}}"
    }
   ]
  },
  {
   "title": "Top $top_write_iops - write iops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($top_write_iops, virtual:kvm:disk:write:iops)",
     "legendFormat": "{{instance_name}} - {{instance_uuid}}"
    }
   ]
  },
  {
   "title": "Top $top_write_kbps - write kbps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($top_write_kbps,virtual:kvm:disk:write:kbps)",
     "legendFormat": "{{instance_name}} - {{instance_uuid}}"
    }
   ]
  }
 ]
}